In [34]:
import numpy as np
import pprint

k_size = 3
kernel = np.ones((k_size, k_size))/k_size**2
image = np.floor(np.random.random((k_size + 4, k_size + 4)) + 0.5)
out = np.zeros(image.shape)

N, M = image.shape
Nk, Mk = kernel.shape

nk_2 = Nk // 2
mk_2 = Mk // 2
print image
for i in range(nk_2, N - nk_2):
    for j in range(mk_2, M - mk_2):
        print image[i-nk_2:i+nk_2+1, j-nk_2:j+nk_2+1]
        out[i, j] = np.sum((image[i-nk_2:i+nk_2+1, j-nk_2:j+nk_2+1]*kernel))
print np.round(out, 4)

[[ 0.  1.  1.  0.  1.  0.  0.]
 [ 1.  0.  1.  1.  0.  1.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  1.  1.  0.]
 [ 1.  1.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  0.]
 [ 1.  1.  1.  0.  1.  0.  0.]]
[[ 0.  1.  1.]
 [ 1.  0.  1.]
 [ 0.  0.  1.]]
[[ 1.  1.  0.]
 [ 0.  1.  1.]
 [ 0.  1.  0.]]
[[ 1.  0.  1.]
 [ 1.  1.  0.]
 [ 1.  0.  0.]]
[[ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]]
[[ 1.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
[[ 0.  1.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  1.]]
[[ 1.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  1.  1.]]
[[ 0.  1.  1.]
 [ 0.  0.  0.]
 [ 1.  1.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  1.  0.]]
[[ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]]
[[ 1.  0.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 1.  1.  0.]
 [ 1.  1.  1.]]
[[ 0.  0.  1.]
 [ 1.  1.  0.]
 [ 0.  0.  0.]]
[[ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  0.  1.]]


In [50]:
a = [[2, 2, 2], [1, 1, 1], [3, 4, 5]]
penis = np.floor(np.random.random((3, 3)) + 0.5)
penis1 = np.floor(np.random.random((3, 3)) + 1.5)
print penis1
print
print penis
print
print np.dot(penis1,penis)
print
print penis1*penis
print
print np.sum(penis1*penis)


[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]

[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]

[[ 0.  2.  2.]
 [ 0.  2.  2.]
 [ 0.  2.  2.]]

[[ 0.  0.  2.]
 [ 0.  2.  0.]
 [ 0.  0.  0.]]

4.0
